[2024-07-17T11:08:49.631+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-17T11:08:49.652+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: init_ods_layer.create_dump manual__2024-07-17T11:08:45.218070+00:00 [queued]>
[2024-07-17T11:08:49.655+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: init_ods_layer.create_dump manual__2024-07-17T11:08:45.218070+00:00 [queued]>
[2024-07-17T11:08:49.655+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-17T11:08:49.660+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): create_dump> on 2024-07-17 11:08:45.218070+00:00
[2024-07-17T11:08:49.668+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=927) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-17T11:08:49.671+0000] {standard_task_runner.py:63} INFO - Started process 929 to run task
[2024-07-17T11:08:49.669+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'init_ods_layer', 'create_dump', 'manual__2024-07-17T11:08:45.218070+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/init_ods.py', '--cfg-path', '/tmp/tmpxdwk4ndl']
[2024-07-17T11:08:49.672+0000] {standard_task_runner.py:91} INFO - Job 147: Subtask create_dump
[2024-07-17T11:08:49.709+0000] {task_command.py:426} INFO - Running <TaskInstance: init_ods_layer.create_dump manual__2024-07-17T11:08:45.218070+00:00 [running]> on host 70110a06f087
[2024-07-17T11:08:49.746+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='init_ods_layer' AIRFLOW_CTX_TASK_ID='create_dump' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T11:08:45.218070+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T11:08:45.218070+00:00'
[2024-07-17T11:08:49.748+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-17T11:08:52.262+0000] {logging_mixin.py:188} INFO - Ошибка при экспорте схемы и данных: Command '['pg_dump', '-U', 'etl_user_3', '-h', '10.82.0.4', '-n', 'source_data', '-f', 'dags/scripts/sql-scripts/ods_migration.sql', 'source']' returned non-zero exit status 1.
[2024-07-17T11:08:52.265+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-17T11:08:52.266+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-17T11:08:52.299+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=init_ods_layer, task_id=create_dump, run_id=manual__2024-07-17T11:08:45.218070+00:00, execution_date=20240717T110845, start_date=20240717T110849, end_date=20240717T110852
[2024-07-17T11:08:52.346+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-17T11:08:52.400+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-17T11:08:52.401+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
