[2024-07-17T11:17:43.425+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-17T11:17:43.435+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: init_ods_layer.create_dump manual__2024-07-17T11:17:38.170549+00:00 [queued]>
[2024-07-17T11:17:43.437+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: init_ods_layer.create_dump manual__2024-07-17T11:17:38.170549+00:00 [queued]>
[2024-07-17T11:17:43.438+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-17T11:17:43.442+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): create_dump> on 2024-07-17 11:17:38.170549+00:00
[2024-07-17T11:17:43.446+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1000) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-17T11:17:43.447+0000] {standard_task_runner.py:63} INFO - Started process 1002 to run task
[2024-07-17T11:17:43.447+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'init_ods_layer', 'create_dump', 'manual__2024-07-17T11:17:38.170549+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/init_ods.py', '--cfg-path', '/tmp/tmps2n9gmg4']
[2024-07-17T11:17:43.449+0000] {standard_task_runner.py:91} INFO - Job 152: Subtask create_dump
[2024-07-17T11:17:43.478+0000] {task_command.py:426} INFO - Running <TaskInstance: init_ods_layer.create_dump manual__2024-07-17T11:17:38.170549+00:00 [running]> on host 70110a06f087
[2024-07-17T11:17:43.518+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='init_ods_layer' AIRFLOW_CTX_TASK_ID='create_dump' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T11:17:38.170549+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T11:17:38.170549+00:00'
[2024-07-17T11:17:43.519+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-17T11:17:45.953+0000] {logging_mixin.py:188} INFO - Ошибка при экспорте схемы и данных: Command '['pg_dump', '-U', 'etl_user_3', '-h', '10.82.0.4', '-n', 'source_data', '-f', 'dags/scripts/sql-scripts/ods_migration.sql', 'source']' returned non-zero exit status 1.
[2024-07-17T11:17:45.956+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-17T11:17:45.956+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-17T11:17:45.968+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=init_ods_layer, task_id=create_dump, run_id=manual__2024-07-17T11:17:38.170549+00:00, execution_date=20240717T111738, start_date=20240717T111743, end_date=20240717T111745
[2024-07-17T11:17:46.018+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-17T11:17:46.047+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-17T11:17:46.047+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
